import pkg from 'pg';
const { Client } = pkg;
import dotenv from 'dotenv';

dotenv.config();

let connStr = process.env.DIRECT_URL;
if (connStr && connStr.includes('#')) {
  connStr = connStr.replace('#LAPTOPKU2026', '%23LAPTOPKU2026');
}

const client = new Client({
  connectionString: connStr,
});

async function main() {
  await client.connect();

  try {
    console.log('Resetting SPK data to Laptop...');

    // Ensure required tables exist (same DDL as setupSpkDb.mjs)
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.kriterias (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kode varchar(50) NOT NULL,
        nama varchar(255) NOT NULL,
        bobot decimal(8,2) NOT NULL,
        atribut varchar(50) NOT NULL,
        created_at timestamp NULL DEFAULT NOW(),
        updated_at timestamp NULL DEFAULT NOW()
      );
    `);

    await client.query(`
      CREATE TABLE IF NOT EXISTS public.sub_kriterias (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kriteria_id bigint NULL REFERENCES public.kriterias(id) ON DELETE CASCADE,
        by_kriteria varchar(255) NULL,
        sub_kriteria varchar(255) NOT NULL,
        skor_sub_kriteria decimal(8,2) NOT NULL,
        atribut varchar(50) NULL,
        created_at timestamp NULL DEFAULT NOW(),
        updated_at timestamp NULL DEFAULT NOW()
      );
    `);

    await client.query(`
      CREATE TABLE IF NOT EXISTS public.alternatifs (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nama varchar(255) NOT NULL,
        c1 decimal(15,2) NULL,
        c2 decimal(15,2) NULL,
        c3 decimal(15,2) NULL,
        c4 decimal(15,2) NULL,
        c5 decimal(15,2) NULL,
        c6 varchar(150) NULL,
        kriteria_id varchar(150) NULL,
        created_at timestamp NULL DEFAULT NOW(),
        updated_at timestamp NULL DEFAULT NOW()
      );
    `);

    await client.query(`
      CREATE TABLE IF NOT EXISTS public.laptops (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kode_unit varchar(50) NULL,
        nama varchar(255) NOT NULL,
        slug varchar(255) NULL,
        merek varchar(150) NULL,
        harga decimal(15,2) NULL,
        tahun int NULL,
        ram_gb int NULL,
        storage_gb int NULL,
        processor varchar(200) NULL,
        layar_inci decimal(6,2) NULL,
        kondisi_baterai int NULL,
        tipe_laptop varchar(150) NULL,
        warna varchar(100) NULL,
        pemilik varchar(255) NULL,
        alamat_pemilik text NULL,
        deskripsi text NULL,
        ketersediaan varchar(50) NULL DEFAULT 'Tersedia',
        gambar varchar(1000) NULL,
        seri varchar(150) NULL,
        c1 decimal(15,2) NULL,
        c2 decimal(15,2) NULL,
        c3 decimal(15,2) NULL,
        c4 decimal(15,2) NULL,
        c5 decimal(15,2) NULL,
        c6 varchar(150) NULL,
        c7 varchar(150) NULL,
        c8 varchar(150) NULL,
        c9 varchar(150) NULL,
        c10 varchar(150) NULL,
        created_at timestamp NULL DEFAULT NOW(),
        updated_at timestamp NULL DEFAULT NOW()
      );
    `);

    await client.query(`
      CREATE TABLE IF NOT EXISTS public.messages (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(255) NOT NULL,
        email varchar(255) NOT NULL,
        nomor varchar(50) NULL,
        subjek varchar(255) NULL,
        pesan text NOT NULL,
        created_at timestamp NULL DEFAULT NOW(),
        updated_at timestamp NULL DEFAULT NOW()
      );
    `);

    // Remove old car table (requested rebrand; destructive)
    await client.query('DROP TABLE IF EXISTS public.mobils;');

    // Clear existing SAW data so laptop criteria + sub criteria match
    await client.query('TRUNCATE TABLE public.alternatifs RESTART IDENTITY;');
    await client.query('TRUNCATE TABLE public.laptops RESTART IDENTITY;');
    await client.query('TRUNCATE TABLE public.kriterias RESTART IDENTITY CASCADE;');

    // Insert laptop criteria
    console.log('Seeding laptop criterias...');
    await client.query(`
      INSERT INTO public.kriterias (kode, nama, bobot, atribut) VALUES
      ('C1', 'Harga', 25.00, 'Cost'),
      ('C2', 'RAM', 15.00, 'Benefit'),
      ('C3', 'Penyimpanan', 15.00, 'Benefit'),
      ('C4', 'Tahun', 20.00, 'Benefit'),
      ('C5', 'Ukuran Layar', 15.00, 'Benefit'),
      ('C6', 'Kondisi Baterai', 10.00, 'Benefit');
    `);

    // Insert sample laptop + alternative values (for SAW)
    console.log('Seeding one sample laptop...');
    await client.query(`
      INSERT INTO public.laptops (
        kode_unit, nama, slug, merek, harga, tahun, ram_gb, storage_gb, processor, layar_inci,
        kondisi_baterai, tipe_laptop, warna, pemilik, alamat_pemilik, deskripsi, ketersediaan,
        c1, c2, c3, c4, c5, c6
      ) VALUES (
        'LP-ASUS-001',
        'ASUS VivoBook 15 OLED',
        'asus-vivobook-15-oled',
        'ASUS',
        12,
        2022,
        16,
        512,
        'Intel Core i5-12500H',
        15.6,
        85,
        'Ultrabook',
        'Silver',
        'Admin Demo',
        'Kediri',
        'Laptop bekas kondisi prima, SSD NVMe, layar OLED.',
        'Tersedia',
        12, 16, 512, 2022, 15.6, '85'
      );
    `);

    await client.query(`
      INSERT INTO public.alternatifs (nama, c1, c2, c3, c4, c5, c6)
      VALUES ('ASUS VivoBook 15 OLED', 12, 16, 512, 2022, 15.6, '85');
    `);

    // Clear caching for postgrest
    await client.query("NOTIFY pgrst, 'reload schema';");

    const [{ rows: kRows }, { rows: sRows }, { rows: aRows }, { rows: lRows }] = await Promise.all([
      client.query('SELECT COUNT(*) AS cnt FROM public.kriterias;'),
      client.query('SELECT COUNT(*) AS cnt FROM public.sub_kriterias;'),
      client.query('SELECT COUNT(*) AS cnt FROM public.alternatifs;'),
      client.query('SELECT COUNT(*) AS cnt FROM public.laptops;'),
    ]);

    console.log('Counts after reset:');
    console.log({
      kriterias: kRows?.[0]?.cnt ?? 0,
      sub_kriterias: sRows?.[0]?.cnt ?? 0,
      alternatifs: aRows?.[0]?.cnt ?? 0,
      laptops: lRows?.[0]?.cnt ?? 0,
    });

    console.log('SPK laptop reset complete. Next: run seedSubKriteria.mjs.');
  } finally {
    await client.end();
  }
}

main().catch((err) => {
  console.error('Laptop reset error:', err);
  process.exit(1);
});

